@startuml
class MessageListener {
    provider : IServiceProvider
    connectionString : string
    bus : IBus
    + MessageListener(provider:IServiceProvider, connectionString:string)
    + Start() : void
    - HandleOrderAccepted(message:OrderAcceptedMessage) : void
    - HandleOrderRejected(message:OrderRejectedMessage) : void
}
@enduml
